const sriLankanBanks = [
  'Bank of Ceylon (BOC)',
  'People\'s Bank',
  'Commercial Bank of Ceylon',
  'Hatton National Bank (HNB)',
  'Sampath Bank',
  'Seylan Bank',
  'Nations Trust Bank (NTB)',
  'DFCC Bank',
  'National Development Bank (NDB)',
  'Pan Asia Banking Corporation (PABC)',
  'Union Bank of Colombo',
  'Amana Bank',
  'Cargills Bank',
  'National Savings Bank (NSB)',
  'Sri Lanka Savings Bank',
  'State Mortgage & Investment Bank',
  'Housing Development Finance Corporation (HDFC)',
  'Pradeshiya Sanwardhana Bank',
  'Regional Development Bank',
  'Sanasa Development Bank',
  'HSBC Sri Lanka',
  'Standard Chartered Bank Sri Lanka',
  'Citibank Sri Lanka',
  'Deutsche Bank Sri Lanka',
  'Indian Bank Sri Lanka',
  'Indian Overseas Bank Sri Lanka',
  'State Bank of India Sri Lanka',
  'MCB Bank Sri Lanka',
  'Habib Bank Sri Lanka',
  'Public Bank Berhad Sri Lanka'
];

module.exports = sriLankanBanks;
